---
- name: Ensure Apache is installed
  yum: name=httpd  state=present

- name: Start Apache
  service: name=httpd state=started enabled=yes

- name: Deploy webpage
  template: src=index.j2 dest=/var/www/html/index.html
  notify:
  - Create healthcheck

- name: Stop iptables
  service: name=iptables state=stopped 
